# Copyright 2025 SUSE LLC
# Licensed under the Apache License, Version 2.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: alien-geeko
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
