# Cluster inventory
# first_nodes are shut down in parallel before last_node

[first_nodes]
pi4-server   ansible_host=192.168.8.7
orin-server  ansible_host=192.168.8.8

[last_node]
rancher-prime  ansible_host=192.168.8.99

[cluster:children]
first_nodes
last_node
